name: ml-project2

channels: 
  - defaults
  - https://conda.anaconda.org/conda-forge
  - pytorch

dependencies:
  - pip
  - numpy
  - transformers
  - pytorch
  - torchvision
  - torchaudio
  - datasets
  - ipython
  - ipykernel
  - scikit-learn